/**
 * Copyright (c) 2017 - 2021, Nordic Semiconductor ASA
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form, except as embedded into a Nordic
 *    Semiconductor ASA integrated circuit in a product or a software update for
 *    such product, must reproduce the above copyright notice, this list of
 *    conditions and the following disclaimer in the documentation and/or other
 *    materials provided with the distribution.
 *
 * 3. Neither the name of Nordic Semiconductor ASA nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * 4. This software, with or without modification, must only be used with a
 *    Nordic Semiconductor ASA integrated circuit.
 *
 * 5. Any software provided in binary form under this license must not be reverse
 *    engineered, decompiled, modified and/or disassembled.
 *
 * THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */



#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#define BLE_ADVERTISING_ENABLED 1

#define NRF_BLE_CONN_PARAMS_ENABLED 1
#define NRF_BLE_CONN_PARAMS_MAX_SLAVE_LATENCY_DEVIATION 499
#define NRF_BLE_CONN_PARAMS_MAX_SUPERVISION_TIMEOUT_DEVIATION 65535
#define NRF_BLE_GATT_ENABLED 1
#define NRF_BLE_GATT_MTU_EXCHANGE_INITIATION_ENABLED 1
#define NRF_BLE_QWR_ENABLED 1
#define NRF_BLE_QWR_MAX_ATTR 0

#define PEER_MANAGER_ENABLED 1
#define PM_MAX_REGISTRANTS 3
#define PM_FLASH_BUFFERS 4
#define PM_CENTRAL_ENABLED 0
#define PM_SERVICE_CHANGED_ENABLED 1
#define PM_PEER_RANKS_ENABLED 1
#define PM_LESC_ENABLED 0
#define PM_RA_PROTECTION_ENABLED 0
#define PM_RA_PROTECTION_TRACKED_PEERS_NUM 8
#define PM_RA_PROTECTION_MIN_WAIT_INTERVAL 4000
#define PM_RA_PROTECTION_MAX_WAIT_INTERVAL 64000
#define PM_RA_PROTECTION_REWARD_PERIOD 10000
#define PM_HANDLER_SEC_DELAY_MS 0

#define BLE_DFU_ENABLED 1
#define NRF_DFU_BLE_BUTTONLESS_SUPPORTS_BONDS 0

#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4
#define GPIOTE_CONFIG_IRQ_PRIORITY 6

#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_LF_SRC 0
#define NRFX_CLOCK_CONFIG_IRQ_PRIORITY 6
#define NRFX_CLOCK_CONFIG_LOG_ENABLED 0

#define NRFX_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 1
#define NRFX_GPIOTE_CONFIG_IRQ_PRIORITY 6
#define NRFX_GPIOTE_CONFIG_LOG_ENABLED 0

#define NRFX_PRS_ENABLED 1
#define NRFX_PRS_BOX_0_ENABLED 0
#define NRFX_PRS_BOX_1_ENABLED 0
#define NRFX_PRS_BOX_2_ENABLED 0
#define NRFX_PRS_BOX_3_ENABLED 0
#define NRFX_PRS_BOX_4_ENABLED 1
#define NRFX_PRS_CONFIG_LOG_ENABLED 0

#define NRFX_UARTE_ENABLED 1
#define NRFX_UARTE0_ENABLED 0
#define NRFX_UARTE_DEFAULT_CONFIG_HWFC 0
#define NRFX_UARTE_DEFAULT_CONFIG_PARITY 0
#define NRFX_UARTE_DEFAULT_CONFIG_BAUDRATE 30801920
#define NRFX_UARTE_DEFAULT_CONFIG_IRQ_PRIORITY 6
#define NRFX_UARTE_CONFIG_LOG_ENABLED 0

#define NRFX_UART_ENABLED 1
#define NRFX_UART0_ENABLED 0
#define NRFX_UART_DEFAULT_CONFIG_HWFC 0
#define NRFX_UART_DEFAULT_CONFIG_PARITY 0
#define NRFX_UART_DEFAULT_CONFIG_BAUDRATE 30924800
#define NRFX_UART_DEFAULT_CONFIG_IRQ_PRIORITY 6
#define NRFX_UART_CONFIG_LOG_ENABLED 0

#define NRF_CLOCK_ENABLED 1
#define CLOCK_CONFIG_LF_SRC 0
#define CLOCK_CONFIG_LF_CAL_ENABLED 1
#define CLOCK_CONFIG_IRQ_PRIORITY 6

#define UART_ENABLED 1
#define UART_DEFAULT_CONFIG_HWFC 0
#define UART_DEFAULT_CONFIG_PARITY 0
#define UART_DEFAULT_CONFIG_BAUDRATE 30801920
#define UART_DEFAULT_CONFIG_IRQ_PRIORITY 6
#define UART_EASY_DMA_SUPPORT 1
#define UART_LEGACY_SUPPORT 1
#define UART0_ENABLED 1
#define UART0_CONFIG_USE_EASY_DMA 1

#define APP_SCHEDULER_ENABLED 1
#define APP_SCHEDULER_WITH_PAUSE 0
#define APP_SCHEDULER_WITH_PROFILER 0

#define APP_TIMER_ENABLED 1
#define APP_TIMER_CONFIG_RTC_FREQUENCY 1
#define APP_TIMER_CONFIG_IRQ_PRIORITY 6
#define APP_TIMER_CONFIG_OP_QUEUE_SIZE 10
#define APP_TIMER_CONFIG_USE_SCHEDULER 0
#define APP_TIMER_KEEPS_RTC_ACTIVE 0
#define APP_TIMER_SAFE_WINDOW_MS 300000
#define APP_TIMER_WITH_PROFILER 0
#define APP_TIMER_CONFIG_SWI_NUMBER 0

#define CRC16_ENABLED 1

#define FDS_ENABLED 1
#define FDS_VIRTUAL_PAGES 3
#define FDS_VIRTUAL_PAGE_SIZE 1024
#define FDS_VIRTUAL_PAGES_RESERVED 0
#define FDS_BACKEND 2
#define FDS_OP_QUEUE_SIZE 4
#define FDS_CRC_CHECK_ON_READ 0
#define FDS_CRC_CHECK_ON_WRITE 0
#define FDS_MAX_USERS 4

#define NRF_BALLOC_ENABLED 1
#define NRF_BALLOC_CONFIG_DEBUG_ENABLED 0
#define NRF_BALLOC_CONFIG_HEAD_GUARD_WORDS 1
#define NRF_BALLOC_CONFIG_TAIL_GUARD_WORDS 1
#define NRF_BALLOC_CONFIG_BASIC_CHECKS_ENABLED 0
#define NRF_BALLOC_CONFIG_DOUBLE_FREE_CHECK_ENABLED 0
#define NRF_BALLOC_CONFIG_DATA_TRASHING_CHECK_ENABLED 0
#define NRF_BALLOC_CLI_CMDS 0

#define NRF_FSTORAGE_ENABLED 1
#define NRF_FSTORAGE_PARAM_CHECK_DISABLED 0
#define NRF_FSTORAGE_SD_QUEUE_SIZE 4
#define NRF_FSTORAGE_SD_MAX_RETRIES 8
#define NRF_FSTORAGE_SD_MAX_WRITE_SIZE 4096

#define NRF_MEMOBJ_ENABLED 1

#define NRF_PWR_MGMT_ENABLED 1
#define NRF_PWR_MGMT_CONFIG_DEBUG_PIN_ENABLED 0
#define NRF_PWR_MGMT_SLEEP_DEBUG_PIN 31
#define NRF_PWR_MGMT_CONFIG_CPU_USAGE_MONITOR_ENABLED 0
#define NRF_PWR_MGMT_CONFIG_STANDBY_TIMEOUT_ENABLED 0
#define NRF_PWR_MGMT_CONFIG_STANDBY_TIMEOUT_S 3
#define NRF_PWR_MGMT_CONFIG_FPU_SUPPORT_ENABLED 1
#define NRF_PWR_MGMT_CONFIG_AUTO_SHUTDOWN_RETRY 1
#define NRF_PWR_MGMT_CONFIG_USE_SCHEDULER 0
#define NRF_PWR_MGMT_CONFIG_HANDLER_PRIORITY_COUNT 3

#define NRF_SECTION_ITER_ENABLED 1

#define NRF_SORTLIST_ENABLED 1
#define NRF_SORTLIST_CONFIG_LOG_ENABLED 0

#define NRF_STRERROR_ENABLED 1

#define NRF_FPRINTF_ENABLED 1
#define NRF_FPRINTF_FLAG_AUTOMATIC_CR_ON_LF_ENABLED 1
#define NRF_FPRINTF_DOUBLE_ENABLED 0

#define NRF_LOG_BACKEND_RTT_ENABLED 1
#define NRF_LOG_BACKEND_RTT_TEMP_BUFFER_SIZE 64
#define NRF_LOG_BACKEND_RTT_TX_RETRY_DELAY_MS 1
#define NRF_LOG_BACKEND_RTT_TX_RETRY_CNT 3
#define NRF_LOG_BACKEND_UART_ENABLED 0
#define NRF_LOG_ENABLED 1
#define NRF_LOG_MSGPOOL_ELEMENT_SIZE 20
#define NRF_LOG_MSGPOOL_ELEMENT_COUNT 8
#define NRF_LOG_ALLOW_OVERFLOW 1
#define NRF_LOG_BUFSIZE 1024
#define NRF_LOG_CLI_CMDS 0
#define NRF_LOG_DEFAULT_LEVEL 4
#define NRF_LOG_DEFERRED 1
#define NRF_LOG_FILTERS_ENABLED 0
#define NRF_LOG_NON_DEFFERED_CRITICAL_REGION_ENABLED 0
#define NRF_LOG_STR_PUSH_BUFFER_SIZE 128
#define NRF_LOG_STR_PUSH_BUFFER_SIZE 128
#define NRF_LOG_USES_COLORS 0
#define NRF_LOG_USES_TIMESTAMP 0
#define NRF_LOG_TIMESTAMP_DEFAULT_FREQUENCY 0
#define NRF_LOG_STR_FORMATTER_TIMESTAMP_FORMAT_ENABLED 1

#define SEGGER_RTT_CONFIG_BUFFER_SIZE_UP 512
#define SEGGER_RTT_CONFIG_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_CONFIG_BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_CONFIG_MAX_NUM_DOWN_BUFFERS 2
#define SEGGER_RTT_CONFIG_DEFAULT_MODE 0

#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_BLE_GAP_DATA_LENGTH 27
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 1
#define NRF_SDH_BLE_CENTRAL_LINK_COUNT 0
#define NRF_SDH_BLE_TOTAL_LINK_COUNT 1
#define NRF_SDH_BLE_GAP_EVENT_LENGTH 6
#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 23
#define NRF_SDH_BLE_GATTS_ATTR_TAB_SIZE 1408
#define NRF_SDH_BLE_VS_UUID_COUNT 1
#define NRF_SDH_BLE_SERVICE_CHANGED 1
#define NRF_SDH_BLE_OBSERVER_PRIO_LEVELS 4

#define BLE_ADV_BLE_OBSERVER_PRIO 1
#define BLE_ANCS_C_BLE_OBSERVER_PRIO 2
#define BLE_ANS_C_BLE_OBSERVER_PRIO 2
#define BLE_BAS_BLE_OBSERVER_PRIO 2
#define BLE_BAS_C_BLE_OBSERVER_PRIO 2
#define BLE_BPS_BLE_OBSERVER_PRIO 2
#define BLE_CONN_PARAMS_BLE_OBSERVER_PRIO 1
#define BLE_CONN_STATE_BLE_OBSERVER_PRIO 0
#define BLE_CSCS_BLE_OBSERVER_PRIO 2
#define BLE_CTS_C_BLE_OBSERVER_PRIO 2
#define BLE_DB_DISC_BLE_OBSERVER_PRIO 1
#define BLE_DFU_BLE_OBSERVER_PRIO 2
#define BLE_DIS_C_BLE_OBSERVER_PRIO 2
#define BLE_GLS_BLE_OBSERVER_PRIO 2
#define BLE_HIDS_BLE_OBSERVER_PRIO 2
#define BLE_HRS_BLE_OBSERVER_PRIO 2
#define BLE_HRS_C_BLE_OBSERVER_PRIO 2
#define BLE_HTS_BLE_OBSERVER_PRIO 2
#define BLE_IAS_BLE_OBSERVER_PRIO 2
#define BLE_IAS_C_BLE_OBSERVER_PRIO 2
#define BLE_LBS_BLE_OBSERVER_PRIO 2
#define BLE_LBS_C_BLE_OBSERVER_PRIO 2
#define BLE_LLS_BLE_OBSERVER_PRIO 2
#define BLE_LNS_BLE_OBSERVER_PRIO 2
#define BLE_NUS_BLE_OBSERVER_PRIO 2
#define BLE_NUS_C_BLE_OBSERVER_PRIO 2
#define BLE_OTS_BLE_OBSERVER_PRIO 2
#define BLE_OTS_C_BLE_OBSERVER_PRIO 2
#define BLE_RSCS_BLE_OBSERVER_PRIO 2
#define BLE_RSCS_C_BLE_OBSERVER_PRIO 2
#define BLE_TPS_BLE_OBSERVER_PRIO 2
#define BSP_BTN_BLE_OBSERVER_PRIO 1

#define NRF_BLE_BMS_BLE_OBSERVER_PRIO 2
#define NRF_BLE_CGMS_BLE_OBSERVER_PRIO 2
#define NRF_BLE_ES_BLE_OBSERVER_PRIO 2
#define NRF_BLE_GATTS_C_BLE_OBSERVER_PRIO 2
#define NRF_BLE_GATT_BLE_OBSERVER_PRIO 1
#define NRF_BLE_GQ_BLE_OBSERVER_PRIO 1
#define NRF_BLE_QWR_BLE_OBSERVER_PRIO 2
#define NRF_BLE_SCAN_OBSERVER_PRIO 1

#define PM_BLE_OBSERVER_PRIO 1

#define NRF_SDH_ENABLED 1
#define NRF_SDH_DISPATCH_MODEL 0
#define NRF_SDH_CLOCK_LF_SRC 0
#define NRF_SDH_CLOCK_LF_RC_CTIV 10
#define NRF_SDH_CLOCK_LF_RC_TEMP_CTIV 10
#define NRF_SDH_CLOCK_LF_ACCURACY NRF_CLOCK_LF_ACCURACY_500_PPM
#define NRF_SDH_REQ_OBSERVER_PRIO_LEVELS 2
#define NRF_SDH_STATE_OBSERVER_PRIO_LEVELS 2
#define NRF_SDH_STACK_OBSERVER_PRIO_LEVELS 2
#define CLOCK_CONFIG_STATE_OBSERVER_PRIO 0
#define POWER_CONFIG_STATE_OBSERVER_PRIO 0
#define RNG_CONFIG_STATE_OBSERVER_PRIO 0
#define NRF_SDH_ANT_STACK_OBSERVER_PRIO 0
#define NRF_SDH_BLE_STACK_OBSERVER_PRIO 0

#define NRF_SDH_SOC_STACK_OBSERVER_PRIO 0
#define NRF_SDH_SOC_ENABLED 1
#define NRF_SDH_SOC_OBSERVER_PRIO_LEVELS 2

#define BLE_DFU_SOC_OBSERVER_PRIO 1

#define CLOCK_CONFIG_SOC_OBSERVER_PRIO 0

#define POWER_CONFIG_SOC_OBSERVER_PRIO 0
#endif //SDK_CONFIG_H

