// BSD 2-Clause License
// 
// Copyright (c) 2024, Tom Keddie
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// 
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
// 
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#pragma once


// Display pins
#define ID130C_PIN_LCD_BL_EN 5
#define ID130C_PIN_LCD_RST_N 11
#define ID130C_PIN_LCD_CS_N 12
#define ID130C_PIN_LCD_DC 16
#define ID130C_PIN_LCD_CLK 19
#define ID130C_PIN_LCD_DATA 20
#define ID130C_PIN_LCD_PWR_N 24

#define ID130C_PIN_TOUCH_EN_N 6
#define ID130C_PIN_TOUCH_INT_N 7

#define ID130C_PIN_HR_SCL 14
#define ID130C_PIN_HR_SDA 15
#define ID130C_PIN_HR_INT 13
#define ID130C_PIN_HR_LDO_EN 23

#define ID130C_PIN_SPI_FLASH_CLK 26
#define ID130C_PIN_SPI_FLASH_DI 25
#define ID130C_PIN_SPI_FLASH_DO 27
#define ID130C_PIN_SPI_FLASH_CE 28

#define ID130C_PIN_UART_TX 22

#define ID130C_PIN_CHARGE_EN_N 1
#define ID130C_PIN_CHARGE_STATUS 10
#define ID130C_PIN_CHARGE_PRESENT_N 9

#define ID130C_PIN_SPARE 0

#if 1
// PCA10040 pin definitions
#undef ID130C_PIN_LCD_RST_N
#define ID130C_PIN_LCD_RST_N 20
#undef ID130C_PIN_LCD_CS_N
#define ID130C_PIN_LCD_CS_N 23
#undef ID130C_PIN_LCD_DC
#define ID130C_PIN_LCD_DC 19
#undef ID130C_PIN_LCD_CLK
#define ID130C_PIN_LCD_CLK 24
#undef ID130C_PIN_LCD_DATA
#define ID130C_PIN_LCD_DATA 22
#undef ID130C_PIN_TOUCH_EN_N
#define ID130C_PIN_TOUCH_EN_N 0
#undef ID130C_PIN_TOUCH_INT_N
#define ID130C_PIN_TOUCH_INT_N 13
#undef ID130C_PIN_LCD_BL_EN
#define ID130C_PIN_LCD_BL_EN 17
#endif


