name: Build and release apps

on:
  push:
    branches: [ "main" ]
    paths:
      - apps/**
      - .github/workflows/apps.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - apps/**
      - .github/workflows/apps.yml
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Get timestamp
        run: echo "MY_TIMESTAMP=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV
      - name: Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          tag_prefix: APPS_
          custom_tag: ${{env.MY_TIMESTAMP}}
      - uses: ./.github/shared/sdk17
      - name: Build blink
        run: |
          cd apps/blink
          make SDK_ROOT=${GITHUB_WORKSPACE}/nRF5_SDK_17.1.0_ddde560 GITHUB_WORKSPACE=${GITHUB_WORKSPACE} VERBOSE=1
          cd ${GITHUB_WORKSPACE}
      - name: Build dfu
        run: |
          cd apps/dfu
          make SDK_ROOT=${GITHUB_WORKSPACE}/nRF5_SDK_17.1.0_ddde560 GITHUB_WORKSPACE=${GITHUB_WORKSPACE} VERBOSE=1
          cd ${GITHUB_WORKSPACE}
      - name: Build demo
        run: |
          cd apps/demo
          make SDK_ROOT=${GITHUB_WORKSPACE}/nRF5_SDK_17.1.0_ddde560 GITHUB_WORKSPACE=${GITHUB_WORKSPACE} VERBOSE=1
          cd ${GITHUB_WORKSPACE}
      - name: Dump filesystem to log
        run: |
          pwd > log.txt
          find . -ls >>log.txt
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            log.txt
            apps/*/_build/*out
            apps/*/_build/*hex
            apps/*/_build/*zip
