name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Fetch tools
        run: |
          wget --no-verbose https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q1-update/+download/gcc-arm-none-eabi-4_9-2015q1-20150306-linux.tar.bz2
          tar xjf gcc-arm-none-eabi-4_9-2015q1-20150306-linux.tar.bz2
          rm -f gcc-arm-none-eabi-4_9-2015q1-20150306-linux.tar.bz2
          wget --no-verbose https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
          tar xjf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz
          rm -f gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz
      - name: Fetch SDKs
        run: |
          wget --no-verbose https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/sdks/nrf5/binaries/nrf5_sdk_17.1.0_ddde560.zip
          unzip -q nrf5_sdk_17.1.0_ddde560.zip
          rm -f nrf5_sdk_17.1.0_ddde560.zip
          wget --no-verbose https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/sdks/nrf5/binaries/nrf5sdk110089a8197.zip
          unzip -d nRF5_SDK_11.0.0_89a8197 -q nrf5sdk110089a8197.zip
          rm -f nrf5sdk110089a8197.zip
      - name: Install nrfutil
        run: |
          mkdir nrfutil
          cd nrfutil
          wget --no-verbose https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil
          chmod 755 nrfutil
          ./nrfutil install nrf5sdk-tools
          cd -
      - name: Build SDK 17.1 bootloader example with our key
        run: |
          cp -f dfu_public_key.c nRF5_SDK_17.1.0_ddde560/examples/dfu/dfu_public_key.c
          cp -f Makefile.posix.17.1 nRF5_SDK_17.1.0_ddde560/components/toolchain/gcc/Makefile.posix
          cd nRF5_SDK_17.1.0_ddde560/examples/dfu/secure_bootloader/pca10040_s132_ble/armgcc
          make SDK_ROOT=${GITHUB_WORKSPACE}/nRF5_SDK_17.1.0_ddde560 GITHUB_WORKSPACE=${GITHUB_WORKSPACE}
          cd -
      - name: Dump filesystem to log
        run: |
          pwd > log.txt
          find . >>log.txt
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: log.txt
          
    
